spring.application.name=demo
<<<<<<< HEAD

server.port=8080
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/placas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234#$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Thymeleaf
spring.thymeleaf.cache=false
=======
>>>>>>> f47ed51836338af13f4154e584401cc10cc62a97
