
spring.application.name=demo

server.port=8080
# MySQL
spring.datasource.url=jdbc:mysql://cdlp-casadelaplacaweb-6f82.i.aivencloud.com:10174/placas_db
spring.datasource.username=cdlp
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Thymeleaf
spring.thymeleaf.cache=false

#Esta informacion se utiliza para obtener acceso a firebase
firebase.bucket.name = cdlp-c1aae.firebasestorage.app
firebase.storage.path = CDLP
firebase.json.path =firebase
firebase.json.file=cdlp-c1aae-firebase-adminsdk-fbsvc-5d779df2a9.json
